apiVersion: apps/v1
kind: Deployment
metadata:
  name: sber-tech-deployment
spec:
  selector:
    matchLabels:
      app: sber-tech
  replicas: 1
  template:
    metadata:
      labels:
        app: sber-tech
    spec:
      containers:
        - name: sber-tech
          image: soppeallod/sbertech
          ports:
            - containerPort: 8080